### PR TITLE
[`CaseInsensitiveCommands`] Casexile, but a Tweak!

### PR DESCRIPTION
**Pull request by KazWolfe**
Someone should probably verify this can be "adopted"... Anyways.

- Uses the same failed command handler logic as Dalamud does. This should always run post-Dalamud.
- Instead of just forcing the first word to lowercase, intelligently look up the command from Lumina.
  - This only makes a difference for GM commands, but hey. It's technically more correct!
  - It may make sense (possibly?) to cache these resolutions to not run a LINQ query every time. However, this isn't running per-frame so I'm not sure if it's a big deal.
- Add optional resolution for Dalamud commands as well, so people can use `/XLPlugins` and all.
  - This will also intelligently search through Dalamud's command registry, meaning plugins that register uppercase commands will be used if found first. (e.g. a plugin registering `/CoolCommand` will now be accessible via `/coolcommand`).

Command resolution order is: as-is command, case-insensitive game command, case-insensitive plugin command, default error response. Meaning:

- The first match for any case-insensitive search is found, so if two plugins register `/someCommand` and `/SomeCommand`, the earlier one registered will take priority when using `/somecommand`.
- If a plugin registers `/MountGuide`, `/MOUNTGUIDE` will always resolve to the game's variant.
  - If the user calls `/MountGuide`, it'll still be handled by the plugin since it's correct case.

I do not know how this plugin will interact with other plugins that perform their own command hooking; I suspect load order would kick in. So if, e.g., a plugin uses the same hook to listen for `/sam` for class-switch purposes, I'm not sure this one will necessarily resolve to that if the user types in `/SAM`.

### CODE REVIEW

**Comment by KazWolfe** [comment]
Makes perfect sense. I'd like to give @RyouBakura some grace time to bring their plugin to API11 - or give consent for this migration as-is. Don't think this is anything critical, so it can hang around for a bit.

**Comment by YsEmei** [comment]
Would it be possible to add ``Command Alias`` support too?

image

**Comment by KazWolfe** [comment]
> Hey. I'm happy that you want to adopt this. Feel free to use any code that seems useful to you.

Neat, thank you for the confirmation. I did take a look at your repo but decided to rewrite from scratch to better handle certain edge cases.

> Would it be possible to add Command Alias support too?

This is a question for Cara, but I suspect that it'd be better to add case insensitivity to that Tweak rather than perform a double-hijack here. I could *probably* add support to this tweak directly, but I'm unsure how that would affect the execution flow and if it'd further mess with context.

**Comment by Caraxi** [comment]
I added support for command alias

**Comment by KazWolfe** [comment]
Looks good and that should work, since you'd still be redirecting the alias prior to the command handler's initial invokes.

**Pull request merged**
