### PR TITLE
Add Tweak: Hunting Log Target Coords

### PR DESCRIPTION
**Pull request by snowoutwith**
Allows clicking on hunting log targets to create map markers; no external dependencies.

Happy to make more changes as necessary!

### CODE REVIEW

**Comment by snowoutwith** [comment]
I'm working on re-doing the zone lookup to use territory/map ids rather than strings which will (a) be more robust and (b) is highlighting some gaps in the coords data.

**Comment by Caraxi** [comment]
the current implementation will only work on english clients so that would be good

**Comment by snowoutwith** [comment]
sorry for the delay! that's all the game-internal strings stripped out, and it works in multiple languages.

I'm not sure whether I've gone overboard with tuples, as I'm not particularly experienced in c# to know when to solidify things into structs or classes.

**Comment by snowoutwith** [comment]
so after thinking about what I want to do with this next, it feels like it's going to grow beyond what makes sense as a tweak (if it ever really did!) so I'm going to close this in favour of a standalone plugin.

thanks for all your work on STP!

**Pull request closed without merging**
