### PR TITLE
[`Legacy Camera Lock`] Fix for DisableWhileAutoRunning not working on plugin start

### PR DESCRIPTION
**Pull request by ryankhart**
Hey, I had noticed after a while that sometimes the DisableWhileAutoRunning feature in 'Legacy Camera Lock' wasn't working until I toggled the option off and back on again. It turns out that every time I disable and reinstall Simple Tweaks and every time that I launch FFXIV, this problem occurs.

After determining that was the cause, I thought it was within my coding abilities to try to solve this myself without creating an issue, and I think I solved it. I mean, I know I solved it for me, but I'll let you be the judge of my changes here messed up anything else.

In particular, is it bad that I removed `Common.FrameworkUpdate -= OnFrameworkUpdate;` or will that cause memory bloating over time for lack of a better word?

### CODE REVIEW

**Comment by Caraxi** [comment]
uh, if you don't disable framework update it will never disable the tweak

**Comment by ryankhart** [comment]
Is this better? I added it back just before `Common.FrameworkUpdate += OnFrameworkUpdate;`

It worked fine without `Common.FrameworkUpdate -= OnFrameworkUpdate;` when I disabled the tweak and the DisableWhileAutoRunning in all the combinations I could think of.

Keep in mind that I don't know how the whole system works just yet. I have yet to make my own plugin from scratch because every idea I have has already been done by someone else, so I resolve to just contribute to other people's projects.

**Comment by ryankhart** [comment]
Oh I think I know why it worked. Did you think I removed this line?
https://github.com/Caraxi/SimpleTweaksPlugin/blob/b684761d05a996b407b1ba806fdec9e2dc7f16e6/Tweaks/LegacyCameraLock.cs#L93

That was still there all along.

I had just removed a second `-=` line, the one included in the ConfigChanged() method that didn't seem like it was doing anything.
https://github.com/Caraxi/SimpleTweaksPlugin/commit/205afea2eb5e35e7ac0e312460f25c9e64293ec5#diff-497b5e7b5d8c3e71c9532c3c96310e61f692f8e4fb53c4b4dfec59efb03a87d2L27-L38

**Comment by Caraxi** [comment]
Okay now that I'm home and had a proper look, turns out its just because I was calling `ConfigChanged()` before `base.Enable()` in the Enable function

**Comment by ryankhart** [comment]
Ok, wow, it was even simpler than I had imagined. I was honestly just cut and pasting the code I know was already working into different places until it worked on first plugin startup without breaking other things.

I think it makes more sense to me now. It didn't work before because the `base.Enable()` hadn't started the tweak's framework update yet.

**Comment by ryankhart** [comment]
And now since my commits line up with your main branch, it now says 0 files have been changed, so I'll go ahead and close this now.

**Pull request closed without merging**
